---
- name: Test Backup Cisco - No Git
  hosts: 127LD_T3_SW-01
  gather_facts: no
  vars:
    # Dùng thư mục /tmp để tránh lỗi Permission (quyền hạn) trong container
    backup_root: "/tmp/backups"
    # Lấy ngày giờ mà không cần gather_facts
    timestamp: "{{ now(fmt='%Y-%m-%d') }}"

  tasks:
    - name: 1. Tao thu muc tam tren AWX
      file:
        path: "{{ backup_root }}"
        state: directory
      delegate_to: localhost

    - name: 2. Lay cấu hình từ Switch Cisco
      cisco.ios.ios_command:
        commands: show running-config
      register: config_output

    - name: 3. Luu cau hinh vao file text tren AWX
      copy:
        content: "{{ config_output.stdout[0] }}"
        dest: "{{ backup_root }}/{{ inventory_hostname }}_{{ timestamp }}.cfg"
      delegate_to: localhost

    - name: 4. Thong bao ket qua (Debug)
      debug:
        msg: "Da luu file thanh cong tai {{ backup_root }}/{{ inventory_hostname }}_{{ timestamp }}.cfg"
