---
- name: Backup Cisco Configuration to GitHub
  hosts: 127LD_T3_SW-01
  gather_facts: no
  vars:
    backup_root: "./backups"
    # Dùng hàm now() thay cho ansible_date_time để không bị lỗi khi gather_facts: no
    timestamp: "{{ now(fmt='%Y-%m-%d') }}"

  tasks:
    - name: Ensure backup directory exists
      file:
        path: "{{ backup_root }}"
        state: directory
      delegate_to: localhost

    - name: Get running configuration from IOS devices
      cisco.ios.ios_command:
        commands: show running-config
      register: config_output

    - name: Save configuration to local file
      copy:
        content: "{{ config_output.stdout[0] }}"
        dest: "{{ backup_root }}/{{ inventory_hostname }}_{{ timestamp }}.cfg"
      delegate_to: localhost  # BẮT BUỘC PHẢI CÓ DÒNG NÀY

    - name: Git Automation - Add, Commit and Push
      shell: |
        git config user.name "AWX Automation"
        git config user.email "awx@yourdomain.com"
        git add .
        git commit -m "Automated backup - {{ timestamp }}"
        git push https://{{ github_user }}:{{ github_token }}@github.com/{{ github_repo_path }}.git main
      delegate_to: localhost
      run_once: true
      environment:
        github_user: "hoangbongvt"
        github_token: "{{ lookup('env', 'GITHUB_TOKEN') }}"
        github_repo_path: "hoangbongvt/cisco-backups"
